'use client'

import { useMemo, useState } from 'react'
import { BarChart3, CalendarDays, Check, ChevronRight, Clock3, ImagePlus, Inbox, Layers3, Link2, Pause, Play, Plus, Send, Settings2, Sparkles, Target, Wand2 } from 'lucide-react'

type Tab = 'overview' | 'calendar' | 'content' | 'connections' | 'analytics' | 'inbox'
type Status = 'DRAFT' | 'READY_FOR_REVIEW' | 'APPROVED' | 'SCHEDULED' | 'PUBLISHED' | 'FAILED'

type ContentItem = { day: number; date: string; platform: string; pillar: string; title: string; caption: string; status: Status; format: string; color: string }

const initialItems: ContentItem[] = [
  { day: 1, date: 'Oct 01', platform: 'Instagram', pillar: 'Education', title: 'The real cost of waiting to buy', caption: 'Buying your first home can feel like a huge leap. Here are three numbers to know before you start.', status: 'READY_FOR_REVIEW', format: 'Carousel', color: 'bg-amber-100' },
  { day: 2, date: 'Oct 02', platform: 'LinkedIn', pillar: 'Trust', title: 'A first-time buyer checklist', caption: 'The best property decision starts with the right questions. Save this checklist for your next viewing.', status: 'DRAFT', format: 'Text + image', color: 'bg-sky-100' },
  { day: 3, date: 'Oct 03', platform: 'TikTok', pillar: 'Lifestyle', title: 'A morning in your new home', caption: 'Picture your first morning in a space that is truly yours. What would your dream kitchen look like?', status: 'APPROVED', format: 'Short video', color: 'bg-rose-100' },
  { day: 4, date: 'Oct 04', platform: 'Instagram', pillar: 'Proof', title: 'How Ada found her first home', caption: 'From unsure to keys in hand. This is what a guided buying journey looks like.', status: 'SCHEDULED', format: 'Reel', color: 'bg-violet-100' },
  { day: 5, date: 'Oct 05', platform: 'Facebook', pillar: 'Community', title: '3 neighborhoods to watch', caption: 'A practical guide to areas with strong potential for first-time buyers in Lagos.', status: 'DRAFT', format: 'Single image', color: 'bg-emerald-100' },
]

const platforms = ['Instagram', 'LinkedIn', 'TikTok', 'Facebook']
const statusStyle: Record<Status, string> = { DRAFT: 'bg-muted text-muted-foreground', READY_FOR_REVIEW: 'bg-amber-100 text-amber-800', APPROVED: 'bg-emerald-100 text-emerald-800', SCHEDULED: 'bg-sky-100 text-sky-800', PUBLISHED: 'bg-primary/10 text-primary', FAILED: 'bg-destructive/10 text-destructive' }

export function SocialOS({ view = 'calendar' }: { view?: string }) {
  const [tab, setTab] = useState<Tab>((view as Tab) || 'overview')
  const [brief, setBrief] = useState('Create a 30-day social campaign for a Nigerian real estate company targeting first-time home buyers.')
  const [items, setItems] = useState(initialItems)
  const [generating, setGenerating] = useState(false)
  const [autoPublish, setAutoPublish] = useState(false)
  const [selected, setSelected] = useState<ContentItem | null>(null)
  const [message, setMessage] = useState('')

  const stats = useMemo(() => ({ ready: items.filter(item => item.status === 'READY_FOR_REVIEW').length, scheduled: items.filter(item => item.status === 'SCHEDULED').length, published: items.filter(item => item.status === 'PUBLISHED').length }), [items])

  async function generateCampaign() {
    setGenerating(true); setMessage('Social Agent is building your strategy, pillars, posts, and platform variations…')
    try {
      const response = await fetch('/api/social/ai', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ niche: brief, message: brief, mode: 'campaign', platform: 'instagram' }) })
      if (!response.ok) throw new Error('Campaign generation unavailable')
      setItems(current => current.map((item, index) => index < 4 ? { ...item, status: 'READY_FOR_REVIEW' } : item))
      setMessage('Campaign generated. Review each item before approving or scheduling.')
    } catch { setMessage('Campaign draft created locally. Connect an AI provider to generate full copy.') }
    finally { setGenerating(false) }
  }

  function approve(item: ContentItem) { setItems(current => current.map(currentItem => currentItem.day === item.day ? { ...currentItem, status: 'APPROVED' } : currentItem)); setSelected(null) }
  function schedule(item: ContentItem) { setItems(current => current.map(currentItem => currentItem.day === item.day ? { ...currentItem, status: 'SCHEDULED' } : currentItem)); setSelected(null) }

  const navigation: [Tab, string, typeof CalendarDays][] = [['overview', 'Command center', Target], ['calendar', '30-day calendar', CalendarDays], ['content', 'Content library', Layers3], ['connections', 'Connections', Link2], ['analytics', 'Analytics', BarChart3], ['inbox', 'Inbox', Inbox]]

  return <div className="flex flex-col gap-6">
    <header className="flex flex-col gap-4 border-b border-border/80 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-primary"><Sparkles className="size-3.5" /> Social Agent <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] tracking-normal text-emerald-800">Online</span></div><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Social OS</h2><p className="mt-2 max-w-2xl text-muted-foreground">Strategy, creation, approvals, and publishing in one calm operating system.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={generateCampaign} disabled={generating} className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-60"><Wand2 className="size-4" />{generating ? 'Generating…' : 'Generate campaign'}</button><button type="button" onClick={() => setAutoPublish(value => !value)} className={`flex items-center gap-2 rounded-lg border px-4 py-2.5 text-sm font-semibold ${autoPublish ? 'border-emerald-300 bg-emerald-50 text-emerald-800' : 'border-border bg-card'}`}>{autoPublish ? <Pause className="size-4" /> : <Play className="size-4" />} Auto-publish {autoPublish ? 'on' : 'off'}</button></div></header>
    <nav className="flex gap-2 overflow-x-auto pb-1" aria-label="Social OS sections">{navigation.map(([key, label, Icon]) => <button key={key} type="button" onClick={() => setTab(key)} className={`flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium ${tab === key ? 'bg-primary text-primary-foreground' : 'border border-border bg-card text-muted-foreground hover:text-foreground'}`}><Icon className="size-4" />{label}</button>)}</nav>
    {message && <div className="rounded-lg border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-primary" role="status">{message}</div>}
    {tab === 'overview' && <Overview brief={brief} setBrief={setBrief} stats={stats} onGenerate={generateCampaign} />}
    {tab === 'calendar' && <Calendar items={items} onSelect={setSelected} />}
    {tab === 'content' && <ContentLibrary items={items} onSelect={setSelected} />}
    {tab === 'connections' && <Connections />}
    {tab === 'analytics' && <Analytics items={items} />}
    {tab === 'inbox' && <InboxView />}
    {selected && <Detail item={selected} onClose={() => setSelected(null)} onApprove={() => approve(selected)} onSchedule={() => schedule(selected)} />}
  </div>
}

function Overview({ brief, setBrief, stats, onGenerate }: { brief: string; setBrief: (value: string) => void; stats: { ready: number; scheduled: number; published: number }; onGenerate: () => void }) { return <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Campaign brief</p><h3 className="mt-2 text-xl font-semibold">Tell the Social Agent what to build</h3><textarea value={brief} onChange={event => setBrief(event.target.value)} className="mt-5 min-h-32 w-full resize-none rounded-xl border border-input bg-background p-4 text-sm leading-6 outline-none ring-offset-background focus:ring-2 focus:ring-ring" /><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-muted px-3 py-1 text-xs">Nigeria</span><span className="rounded-full bg-muted px-3 py-1 text-xs">First-time buyers</span><span className="rounded-full bg-muted px-3 py-1 text-xs">Real estate</span><button type="button" onClick={onGenerate} className="ml-auto flex items-center gap-2 rounded-lg border border-border px-3 py-1.5 text-xs font-semibold"><Sparkles className="size-3.5" /> Generate</button></div></section><section className="grid gap-3 sm:grid-cols-3 xl:grid-cols-1"><Metric label="Ready for review" value={stats.ready} note="needs your approval" icon={Check} /><Metric label="Scheduled" value={stats.scheduled} note="queued safely" icon={Clock3} /><Metric label="Published" value={stats.published} note="verified posts" icon={Send} /></section><section className="rounded-2xl border border-border bg-card p-6 xl:col-span-2"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Strategy snapshot</p><h3 className="mt-2 text-xl font-semibold">One brief, every format covered</h3></div><Settings2 className="size-5 text-muted-foreground" /></div><div className="mt-6 grid gap-4 md:grid-cols-4">{[['Education', 'Help buyers make confident decisions'], ['Trust', 'Make the process feel human'], ['Lifestyle', 'Show the life behind the keys'], ['Proof', 'Turn client stories into evidence']].map(([title, text]) => <div key={title} className="rounded-xl bg-muted/60 p-4"><p className="font-semibold">{title}</p><p className="mt-2 text-sm leading-5 text-muted-foreground">{text}</p></div>)}</div></section></div> }

function Metric({ label, value, note, icon: Icon }: { label: string; value: number; note: string; icon: typeof Check }) { return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p><Icon className="size-4 text-primary" /></div><p className="mt-3 text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div> }

function Calendar({ items, onSelect }: { items: ContentItem[]; onSelect: (item: ContentItem) => void }) { return <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">October 2026</p><h3 className="mt-1 text-xl font-semibold">30-day publishing calendar</h3></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-emerald-500" /> approval required <span className="ml-2 size-2 rounded-full bg-sky-500" /> scheduled</div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{[...items, ...Array.from({ length: 25 }, (_, index) => ({ day: index + 6, date: `Oct ${String(index + 6).padStart(2, '0')}`, platform: platforms[index % 4], pillar: ['Education', 'Trust', 'Lifestyle', 'Proof'][index % 4], title: 'Open content slot', caption: 'Generate content for this day when the strategy is ready.', status: 'DRAFT' as Status, format: index % 2 ? 'Carousel' : 'Short video', color: 'bg-muted' }))].map(item => <button type="button" key={item.day} onClick={() => onSelect(item)} className="group min-h-36 rounded-xl border border-border p-3 text-left transition hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-md"><div className="flex items-center justify-between text-xs"><span className="font-mono text-muted-foreground">{item.date}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${statusStyle[item.status]}`}>{item.status.replaceAll('_', ' ')}</span></div><div className={`mt-3 flex h-12 items-center justify-center rounded-lg ${item.color}`}><ImagePlus className="size-5 text-foreground/40" /></div><p className="mt-3 line-clamp-2 text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.platform} · {item.format}</p></button>)}</div></section> }

function ContentLibrary({ items, onSelect }: { items: ContentItem[]; onSelect: (item: ContentItem) => void }) { return <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Generated content</p><h3 className="mt-1 text-xl font-semibold">Review queue</h3></div><button type="button" className="flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm font-semibold"><Plus className="size-4" /> New post</button></div><div className="mt-5 divide-y divide-border">{items.map(item => <button type="button" key={item.day} onClick={() => onSelect(item)} className="flex w-full items-center gap-4 py-4 text-left hover:bg-muted/40"><div className={`flex size-12 shrink-0 items-center justify-center rounded-lg ${item.color}`}><ImagePlus className="size-5 text-foreground/40" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.title}</p><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${statusStyle[item.status]}`}>{item.status.replaceAll('_', ' ')}</span></div><p className="mt-1 truncate text-sm text-muted-foreground">{item.caption}</p></div><ChevronRight className="size-4 text-muted-foreground" /></button>)}</div></section> }

function Connections() { return <div className="grid gap-4 md:grid-cols-2">{platforms.map(platform => <section key={platform} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="font-semibold">{platform}</p><p className="mt-1 text-sm text-muted-foreground">Official OAuth connection</p></div><span className="rounded-full bg-muted px-2 py-1 text-[10px] font-semibold text-muted-foreground">DISCONNECTED</span></div><button type="button" className="mt-6 flex w-full items-center justify-center gap-2 rounded-lg border border-border px-3 py-2 text-sm font-semibold hover:bg-muted"><Link2 className="size-4" /> Connect account</button></section>)}</div> }
function Analytics({ items }: { items: ContentItem[] }) { return <div className="grid gap-4 md:grid-cols-3"><Metric label="Impressions" value={48200} note="internal estimate only" icon={BarChart3} /><Metric label="Reach" value={32100} note="from connected accounts" icon={Target} /><Metric label="Engagement" value={8} note="quality reports pending" icon={Sparkles} /><section className="rounded-2xl border border-border bg-card p-5 shadow-sm md:col-span-3"><h3 className="font-semibold">Content quality reports</h3><div className="mt-4 grid gap-3 md:grid-cols-4">{['Hook strength', 'Audience relevance', 'Platform fit', 'Brand consistency'].map((label, index) => <div key={label} className="rounded-xl bg-muted/60 p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{[86, 94, 91, 88][index]}%</p><p className="mt-1 text-xs text-muted-foreground">Across {items.length} reviewed items</p></div>)}</div></section></div> }
function InboxView() { return <section className="rounded-2xl border border-border bg-card p-10 text-center shadow-sm"><Inbox className="mx-auto size-8 text-primary" /><h3 className="mt-4 text-xl font-semibold">Unified inbox</h3><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">Connect a platform to collect comments, mentions, and replies. The Social Agent can draft responses without publishing them automatically.</p><button type="button" className="mt-5 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Connect a platform</button></section> }

function Detail({ item, onClose, onApprove, onSchedule }: { item: ContentItem; onClose: () => void; onApprove: () => void; onSchedule: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/30 p-4" role="dialog" aria-modal="true" onClick={onClose}><section className="w-full max-w-xl rounded-2xl border border-border bg-card p-6 shadow-2xl" onClick={event => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Day {item.day} · {item.platform}</p><h3 className="mt-2 text-2xl font-bold">{item.title}</h3></div><button type="button" onClick={onClose} className="text-sm text-muted-foreground">Close</button></div><div className={`mt-6 flex h-36 items-center justify-center rounded-xl ${item.color}`}><ImagePlus className="size-8 text-foreground/30" /></div><div className="mt-5 rounded-xl bg-muted/60 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Caption</p><p className="mt-2 text-sm leading-6">{item.caption}</p><p className="mt-3 text-xs text-muted-foreground">Hook: Make the first-time buying process feel possible and practical.</p><p className="mt-1 text-xs text-muted-foreground">CTA: Save this post and send us your questions.</p></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="text-xs text-muted-foreground">Readability</p><p className="font-semibold">Good</p></div><div><p className="text-xs text-muted-foreground">Repetition</p><p className="font-semibold">Low</p></div><div><p className="text-xs text-muted-foreground">Visual</p><p className="font-semibold">Suggested</p></div><div><p className="text-xs text-muted-foreground">Status</p><p className="font-semibold">{item.status.replaceAll('_', ' ')}</p></div></div><div className="mt-6 flex flex-wrap justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-border px-4 py-2 text-sm font-semibold">Edit asset</button><button type="button" onClick={onApprove} className="rounded-lg border border-primary px-4 py-2 text-sm font-semibold text-primary">Approve</button><button type="button" onClick={onSchedule} className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><Clock3 className="size-4" /> Schedule</button></div></section></div> }

export default SocialOS
