'use client'

import { useEffect, useState } from 'react'
import { Check, Clapperboard, FileText, Image as ImageIcon, Mic2, Play, Search, Upload, WandSparkles } from 'lucide-react'

type Asset = { id: string; type: string; status: string; provider?: string | null }
type Video = { id: string; title: string; topic: string; stage: string; status: string; research?: string | null; script?: string | null; assets: Asset[]; views: number; likes: number; comments: number }
const stages = [{ key: 'RESEARCH', label: 'Research', icon: Search }, { key: 'SCRIPT', label: 'AI Script', icon: FileText }, { key: 'VOICEOVER', label: 'Voiceover', icon: Mic2 }, { key: 'STOCK_VIDEO', label: 'Stock video', icon: Clapperboard }, { key: 'THUMBNAIL', label: 'Thumbnail', icon: ImageIcon }, { key: 'UPLOAD', label: 'Upload', icon: Upload }]

export function YouTubeOS() {
  const [videos, setVideos] = useState<Video[]>([]); const [topic, setTopic] = useState(''); const [selected, setSelected] = useState<Video | null>(null); const [notice, setNotice] = useState('')
  async function load() { const res = await fetch('/api/youtube'); if (res.ok) setVideos(await res.json()) }
  useEffect(() => { load() }, [])
  async function create() { if (!topic.trim()) return; const res = await fetch('/api/youtube', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ topic }) }); const data = await res.json(); if (!res.ok) return setNotice(data.error); setVideos((v) => [data, ...v]); setSelected(data); setTopic(''); setNotice('Video workflow created. Start with research.'); }
  async function generate(kind: 'research' | 'script') { if (!selected) return; setNotice(kind === 'research' ? 'Researching topic…' : 'Writing script…'); const res = await fetch('/api/youtube/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: selected.id, kind }) }); const data = await res.json(); if (!res.ok) return setNotice(data.error); setSelected(data); setVideos((items) => items.map((item) => item.id === data.id ? data : item)); setNotice(kind === 'research' ? 'Research ready. Review it, then generate the script.' : 'Script ready for voiceover production.'); }
  const currentStage = selected ? stages.findIndex((stage) => stage.key === selected.stage) : 0
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Faceless YouTube OS</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Turn a topic into a channel asset.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Research, script, produce, and prepare videos for upload from one focused pipeline.</p></div><div className="flex items-center gap-2 rounded-full border border-border px-3 py-1.5 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-amber-400" />Provider connections optional</div></div>
  <div className="grid gap-6 lg:grid-cols-[1fr_1.45fr]"><section className="space-y-4"><div className="rounded-xl border border-border bg-card p-5"><div className="flex items-center gap-2 text-sm font-semibold"><WandSparkles className="size-4 text-primary" />Start a production</div><textarea value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="e.g. Why calm systems beat hustle culture" className="mt-4 min-h-28 w-full resize-none rounded-md border border-input bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-ring" /><button onClick={create} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground"><Play className="size-4" />Create video workflow</button>{notice && <p className="mt-3 text-xs text-muted-foreground">{notice}</p>}</div><div className="space-y-2">{videos.map((video) => <button key={video.id} onClick={() => setSelected(video)} className={`w-full rounded-lg border p-4 text-left transition-colors ${selected?.id === video.id ? 'border-primary bg-primary/5' : 'border-border bg-card hover:border-primary/40'}`}><div className="flex items-center justify-between"><p className="truncate pr-4 text-sm font-medium">{video.title}</p><span className="text-[10px] uppercase tracking-wider text-muted-foreground">{video.stage}</span></div><p className="mt-2 text-xs text-muted-foreground">{video.views} views · {video.likes} likes</p></button>)}</div></section>
  <section className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Production pipeline</p><h3 className="mt-1 text-lg font-semibold">{selected?.title ?? 'Select a video workflow'}</h3></div>{selected && <span className="rounded-full bg-accent px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider">{selected.status}</span>}</div>{selected ? <><div className="mt-6 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{stages.map((stage, index) => { const Icon = stage.icon; const done = index < currentStage; const active = index === currentStage; return <div key={stage.key} className={`rounded-lg border p-3 ${active ? 'border-primary bg-primary/10' : 'border-border'}`}><div className="flex items-center justify-between"><Icon className="size-4 text-primary" />{done && <Check className="size-3.5 text-emerald-500" />}</div><p className="mt-3 text-xs font-medium">{stage.label}</p></div> })}</div><div className="mt-6 rounded-lg bg-background p-4"><div className="flex flex-wrap gap-2"><button onClick={() => generate('research')} className="rounded-md border border-border px-3 py-2 text-xs font-medium hover:bg-accent">Generate research</button><button onClick={() => generate('script')} disabled={!selected.research} className="rounded-md bg-primary px-3 py-2 text-xs font-medium text-primary-foreground disabled:opacity-40">Generate AI script</button></div>{selected.research && <div className="mt-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Research notes</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{selected.research}</p></div>}{selected.script && <div className="mt-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Editable script</p><textarea value={selected.script} onChange={(e) => setSelected({ ...selected, script: e.target.value })} className="mt-2 min-h-52 w-full rounded-md border border-input bg-card p-3 text-sm leading-6 outline-none focus:ring-2 focus:ring-ring" /></div>}</div></> : <div className="flex min-h-80 items-center justify-center text-center text-sm text-muted-foreground">Create or select a workflow to manage its production stages.</div>}</section></div></div>
}
