import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export default async function CampaignsPage() {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) redirect('/login')
  const campaigns = await prisma.leadCampaign.findMany({ where: { ownerId: session.user.id }, include: { leads: true, messages: true }, orderBy: { updatedAt: 'desc' } })
  return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-5xl px-6 py-8"><a href="/leads" className="text-sm text-muted-foreground hover:text-foreground">← Back to CRM</a><p className="mt-8 font-mono text-xs uppercase tracking-[0.22em] text-muted-foreground">Module 8 / Campaigns</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Outreach campaigns</h1><p className="mt-2 text-sm text-muted-foreground">Three-touch sequences over seven days, ready for sandbox testing.</p><div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-5"><p className="text-xs text-muted-foreground">Campaigns</p><p className="mt-2 text-3xl font-semibold">{campaigns.length}</p></div><div className="rounded-2xl border border-border bg-card p-5"><p className="text-xs text-muted-foreground">Leads enrolled</p><p className="mt-2 text-3xl font-semibold">{campaigns.reduce((sum, campaign) => sum + campaign.leads.length, 0)}</p></div><div className="rounded-2xl border border-border bg-card p-5"><p className="text-xs text-muted-foreground">Messages drafted</p><p className="mt-2 text-3xl font-semibold">{campaigns.reduce((sum, campaign) => sum + campaign.messages.length, 0)}</p></div></div><section className="mt-8 flex flex-col gap-3">{campaigns.length === 0 ? <div className="rounded-2xl border border-dashed border-border p-8 text-sm text-muted-foreground">No campaigns yet. Find leads first, then create a campaign.</div> : campaigns.map((campaign) => <article key={campaign.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-medium">{campaign.name}</h2><p className="mt-1 text-sm text-muted-foreground">{campaign.niche || 'General'} · {campaign.location || 'Remote'}</p></div><span className="rounded-full bg-muted px-3 py-1 text-xs">{campaign.status}</span></div><div className="mt-4 flex gap-4 text-xs text-muted-foreground"><span>{campaign.leads.length} leads</span><span>{campaign.messages.length} messages</span><span>3 touches / 7 days</span></div></article>)}</section></div></main>
}

